[package]
name = "nest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.10", features = ["multipart", "headers", "http2", "ws"] }
axum_typed_multipart = "^0.3.0"
bytes = "1.4.0"
futures = "0.3.27"
hyper = { version = "0.14.25", features = ["full"] }
object_store = "0.5.5"
serde = { version = "1.0.155", features = ["derive"] }
tokio = { version = "1.26.0", features = ["full"] }
tower = "0.4.13"
surrealdb = "1.0.0-beta.9+20230402"
serde_json = "1.0.95"
tinytemplate = "1.2.1"
