[package]
name = "nest"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6.10", features = ["multipart", "headers", "http2", "ws"] }
axum_typed_multipart = "^0.3.0"
bytes = "1.4.0"
object_store = "0.5.5"
serde = { version = "1.0.155", features = ["derive"] }
tokio = { version = "1.26.0", features = ["full"] }
tower = "0.4.13"
surrealdb = "1.0.0-beta.9+20230402"
serde_json = "1.0.95"
tinytemplate = "1.2.1"
async-trait = "0.1.68"
log = "0.4.17"
env_logger = "0.10.0"

[dev-dependencies]
anyhow = "1"
httpc-test = "0.1.1"

[profile.release]
lto = true