[package]
name = "nest"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.68"
axum = { version = "0.6.10", features = ["multipart", "headers"] }
axum_typed_multipart = "^0.3.0"
bytes = "1.4.0"
env_logger = "0.10.0"
futures = "0.3.28"
log = "0.4.17"
object_store = "0.5.5"
serde = { version = "1.0.155", features = ["derive"] }
serde_json = "1.0.95"
surrealdb = "1.0.0-beta.9+20230402"
tinytemplate = "1.2.1"
tokio = { version = "1.26.0", features = ["full"] }
tower = "0.4.13"

[dev-dependencies]
anyhow = "1"
httpc-test = "0.1.1"

[profile.release]
lto = true
