[application]
host = '127.0.0.1'
port = 8080

[persistence]
[persistence.object_storage]
path = './simple-index'

[persistence.database]
host = '127.0.0.1'
port = 5432
username = 'nest-user'
password = 'nest-secret'
name = 'postgres'
