version: '3'

volumes:
  db:

services:
  database:
    image: docker.io/postgres:latest 
    restart: always
    environment:
      - POSTGRES_DB=nest
      - POSTGRES_USER=nest-user
      - POSTGRES_PASSWORD=nest-secret
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
