version: '3'

volumes:
  nest_db:

services:
  db:
    image: docker.io/postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=nest
      - POSTGRES_USER=nest-user
      - POSTGRES_PASSWORD=nest-secret
    ports:
      - '5432:5432'
    volumes:
      - nest_db:/var/lib/postgresql/data
  nest:
    image: nest
    build:
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./configurations/config.docker.toml:/app/config.default.toml
    ports:
      - '8080:5037'
