name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      database:
        image: postgres
        env:
          POSTGRES_USER: nest-user
          POSTGRES_PASSWORD: nest-secret
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Set up rust
        uses: actions/checkout@v2
      - name: Install dev crates
        run: |
          cargo install cargo-audit
      - name: Build
        run: cargo build -v
      - name: Test
        run: cargo test -v
      - name: Lint
        run: cargo clippy -v -- -D warnings
      - name: Audit
        run: cargo audit
